### PR TITLE
Update all dependencies and get tests to work once more.

### PR DESCRIPTION
**Pull request by Levdbas**
PR #61 seems at a stale. To separate concerns, I've just focused on updating all dependencies and get the tests to run both locally and on Travis. Also added minimal engine required by this package.

### CODE REVIEW

**Comment by Levdbas** [comment]
Hi @civan , I hope you are able to look into this PR. :)

**Comment by civan** [comment]
Hi @Levdbas thanks for taking care of this, sure we can merge it, thanks again for your help!

**Comment by Levdbas** [comment]
Hi @civan , glad I van lend a hand. Dan you release a new version on NPM as well? Thanks!

**Comment by civan** [comment]
It is done @Levdbas thanks again!

**Pull request merged**
